export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const LOGOUT = "LOGOUT";
export const AUTH_CLEAR_ERROR = "AUTH_CLEAR_ERROR";

export const REFRESH_ACCESS_TOKEN_FROM_SERVER_SUCCESS =
  "REFRESH_ACCESS_TOKEN_FROM_SERVER_SUCCESS";

export const AUTH_CHECKED_STATE = "AUTH_CHECKED_STATE";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const COUNT = "COUNT";
